# Default values for helm-crm.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: umarfd/data-pesanan
  pullPolicy: IfNotPresent
  tag: "1.16.0"

configMap:
  enabled: true
  data:
    PORT: "8070"

imagePullSecrets:
  - ghcr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8070

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: pesanan.uwuw.my.id
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 8070
readinessProbe:
  httpGet:
    path: /
    port: 8070

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

secret: {}

migrate:
  enabled: true
  env:
    - name: DATABASE_URL
      value: "postgresql://postgres:postgres@postgres:5432/data_pesanan"

postgres:
  enabled: true
  user: postgres
  password: postgres
  db: data_pesanan
  port: 5432

wwebjs:
  enabled: false
  storage: 1Gi
  storageClass: standard
